### ISSUE TITLE
OCR0021: OCR data from Google Books

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/create_ocr_data#14]
### Descriptions:
We have Modern book format printed Tibetan books OCRed by Google under the project called google books, so we need to use the output from that OCR which is in html, use that to take the bounding box and crop the line images and upload to the s3 and then creating a csv for the transcripts. Downloaded google books data are in the google drive at https://drive.google.com/drive/u/1/folders/15Y-PnZBT1JtrZX1ck-RT4Hd1oWU9VA7b

### Completion Criteria:
Line images uploaded to the s3 and transcripts in the csv, along with its image name and metadata if present.

### Implementation Plan
![ocr](https://github.com/OpenPecha/Requests/assets/52191545/2d4ec0fa-57fe-4de7-94f2-03083fd2da4f)

### Subtask 
- [ ] Set up EC2 Server with credentials
- [ ] Set up google drive credentials
- [ ] Set up aws credentials
- [ ] Download work zip files from Google drive.
- [ ] Extract work zip files
- [ ] Run the filtering scripts
- [ ] Reorganize the output into zip files
- [ ] Upload to aws server
